# .github/workflows/ci.yml
name: CI for ForestApp

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-validate:
    name: Validación de Linter y Tests
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar Linter (ESLint)
        run: npm run lint

      - name: Ejecutar Tests (Jest)
        run: npm run test
